In [4]:
import pandas as pd

In [5]:
df=pd.read_csv('details.csv')

In [6]:
df.head()

,Sr. No.,Enrollment Number,Name,Course,Year,Semester,Specialization,Email Id,Contact Number
0,1,202210101330001,Vedansh Mishra,BCA,3rd,5th,AI,vedanshmishra_202210101330001@srmu.ac.in,9.555301e+09
1,2,202210101330002,Shikhar Singh,BCA,3rd,5th,AI,shikharsingh_202210101330002@srmu.ac.in,6.306021e+09
2,3,202210101330003,Harsh Singh,BCA,3rd,5th,AI,harshsingh_202210101330003@srmu.ac.in,9.555749e+09
3,4,202210101330004,Abhay Pratap Singh,BCA,3rd,5th,AI,NaN,9.555229e+09
4,5,202210101330005,Abhay Pratap Singh,BCA,3rd,5th,AI,Abhaypratapsingh_202210101330005@srmu.ac.in,8.209724e+09

In [7]:
df['First_name'] = df['Name'].apply(lambda x: x.split(' ')[0])
df['Last_name'] = df['Name'].apply(lambda x: ' '.join(x.split(' ')[1:]))

In [8]:
df.head()

,Sr. No.,Enrollment Number,Name,Course,Year,Semester,Specialization,Email Id,Contact Number,First_name,Last_name
0,1,202210101330001,Vedansh Mishra,BCA,3rd,5th,AI,vedanshmishra_202210101330001@srmu.ac.in,9.555301e+09,Vedansh,Mishra
1,2,202210101330002,Shikhar Singh,BCA,3rd,5th,AI,shikharsingh_202210101330002@srmu.ac.in,6.306021e+09,Shikhar,Singh
2,3,202210101330003,Harsh Singh,BCA,3rd,5th,AI,harshsingh_202210101330003@srmu.ac.in,9.555749e+09,Harsh,Singh
3,4,202210101330004,Abhay Pratap Singh,BCA,3rd,5th,AI,NaN,9.555229e+09,Abhay,Pratap Singh
4,5,202210101330005,Abhay Pratap Singh,BCA,3rd,5th,AI,Abhaypratapsingh_202210101330005@srmu.ac.in,8.209724e+09,Abhay,Pratap Singh

In [9]:
df.to_csv('new.csv')